export const ADD_FLASH_MESSAGE = 'ADD_FLASH_MESSAGE';
export const DELETE_FLASH_MESSAGE = 'DELETE_FLASH_MESSAGE';
/** Flash Messages */
export const SET_CURRENT_USER = 'SET_CURRENT_USER';
export const LOGOUT = "LOGOUT";
/**AUTH */
export const ADD_ITEM = 'ADD_ITEM';
export const BULK_ADD = 'BULK_ADD';
export const SHOW_ITEM_DETAILS = 'SHOW_ITEM_DETAILS';
export const SHOW_ADD_ITEM_FORM = 'SHOW_ADD_ITEM_FORM';
export const SHOW_UPDATE_INVENTORY = 'SHOW_UPDATE_INVENTORY';
export const UPDATE_INVENTORY = 'UPDATE_INVENTORY';
export const UPDATE_ITEM = 'UPDATE_ITEM';
/** Items */
export const ADD_TO_CURRENT_RECEIPT = 'ADD_TO_CURRENT_RECEIPT';
export const EDIT_CURRENT_RECEIPT = 'EDIT_CURRENT_RECEIPT';
export const SUBMIT_RECEIPT = 'SUBMIT_RECEIPT';
export const DELETE_RECEIPT_ITEM = 'DELETE_RECEIPT_ITEM';
export const ADD_TO_LIST_OF_RECEIPTS = 'ADD_TO_LIST_OF_RECEIPTS';
export const VIEW_RECEIPTS = 'VIEW_RECEIPTS';
export const GET_ALL_MOST_BOUGHT_ITEMS = 'GET_ALL_MOST_BOUGHT_ITEMS';
export const RECEIPT_DETAILS_MODAL = 'RECEIPT_DETAILS_MODAL';
/** receipt */
export const GET_TRANSACTIONS = 'GET_TRANSACTIONS';
export const CREATE_NEW_CUSTOMER = 'CREATE_NEW_CUSTOMER';
export const GET_CUSTOMERS = 'GET_CUSTOMERS';
export const DELETE_CUSTOMER = 'DELETE_CUSTOMER';
/** Customer */